### ISSUE TITLE
Add setting for changing network caching value and maybe other advanced options

### ISSUE THREAD

**Issue by zeroepoch** [autoandshare/HeadVR#2]
I'd like to use HeadVR to view a live RTSP stream. It works great, but there is a few seconds delay. I believe if network caching parameters were exposed maybe this issue could be improved. By reducing network caching on my PC it does appear to help reduce the latency. I'm not sure how this option gets exposed on Android. I believe there is a setting for this in the regular Android app.

**Comment by autoandshare** [comment]
VLC setting has been included.

**Comment by zeroepoch** [comment]
Awesome! Works great.
