### ISSUE TITLE
Played video is upside down - no way to flip orientation internally.

### ISSUE THREAD

**Issue by Spaceman333** [autoandshare/HeadVR#4]
I slotted in my phone into the VR headset that I have, which specifically has a hole on the right side for an audio jack plug in - and does not have such a hole on the left side.

So I turn on a video, but then notice that it is upside down. I look into the settings and it does not:
1. no auto orient
2. no settings allow me to manually flip the image

If I turn the phone to face the other way, then I won't be able to plug in my headphones.

Please advice how can I overcome this issue.

**Comment by autoandshare** [comment]
added option to change orientation
